blank_issues_enabled: false
contact_links:
  - name: Discord Community
    url: https://dsc.gg/ceruleancoders
    about: Join the Discord Community for more awesome stuff!
  - name: Questions/Doubts
    url: https://github.com/CeruleanCodersComm/community/discussions
    about: Please use this questions/doubts and other stuff
